name: elaarra_calorie_tracker
description: A beautiful calorie tracking app with AI features to help you achieve your health goals.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^6.1.0
  firebase_storage: ^12.3.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.0
  cached_network_image: ^3.3.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.0
  intl: ^0.19.0
  flutter_animate: ^4.1.1
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
  uses-material-design: true
  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/CormorantGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CormorantGaramond-Bold.ttf
          weight: 700
    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/NeueMontreal-Light.otf
          weight: 300
        - asset: assets/fonts/NeueMontreal-Regular.otf
          weight: 400
        - asset: assets/fonts/NeueMontreal-Medium.otf
          weight: 500
        - asset: assets/fonts/NeueMontreal-Bold.otf
          weight: 700
